# Generated by Django 4.2 on 2023-04-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockaid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='choose',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='description',
        ),
    ]
