# Generated by Django 4.2 on 2023-06-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockaid', '0002_rename_cover_post_choose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torso_color', models.CharField(max_length=7)),
                ('pockets_color', models.CharField(max_length=7)),
                ('left_sleeve_color', models.CharField(max_length=7)),
                ('right_sleeve_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
