# Generated by Django 4.2 on 2023-06-13 16:15

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blockaid', '0009_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
