# Generated by Django 4.2 on 2023-06-13 16:20

from django.db import migrations

def create_sizes(apps, schema_editor):
    Size = apps.get_model('blockaid', 'Size')
    sizes = ['Small', 'Medium', 'Large']

    for size in sizes:
        Size.objects.create(size = size)

class Migration(migrations.Migration):

    dependencies = [
        ('blockaid', '0010_alter_sizes_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
        migrations.RunPython(create_sizes),
    ]
