# Generated by Django 4.2 on 2023-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockaid', '0012_order_product_orderdetails_order_details_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='qunatity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='color',
            name='is_in_shop',
            field=models.BooleanField(default=False),
        ),
    ]
