# Generated by Django 4.2 on 2023-07-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockaid', '0014_remove_product_name_product_quantity_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
