# Generated by Django 4.2 on 2023-07-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockaid', '0017_cart_remove_order_details_order_created_at_cartitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cart_items',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(through='blockaid.OrderDetails', to='blockaid.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='nametest', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
